### ISSUE TITLE
(GUI) Relationship text box

### ISSUE THREAD

**Issue by GrantHartenstine** [mucs420f19/MMouseLLC#139]
Arrows between classes need to have a quantifier attached to the line to show number relationships (like 1:1 or 1:many etc.)
The user needs to be able to configure the actual relationship

Primary: Lauren
Alt: Matt, Eric

Estimated Time: 10 Hours or more

**Comment by lndeaver** [comment]
Logged time:
10/24
Looked at JavaFx work - 1.5 hours

10/25
Looked at JavaFx work - 2.0 hours

10/28
JavaFx research - 3 hours

10/29
JavaFx research - 2.5 hours

10/30
Looked at GUI code - 0.5 hours

11/5
Began trying to work on quantifier issue for arrows - 2 hours

11/6
Worked on trying to sort out how to get quantifiers working with text boxes/labels - 4 hours

11/7
More quantifier work - 3 hours

11/8
Still more quantifier work -2 hours

11/10
Got a base quantifier working, need to fix up the shifting and add an edit button to be able to change it once inputted - 2 hours (maybe more later)

**Comment by lndeaver** [comment]
11/10
same as earlier, fixing draggable updating where the quantifier is, right now only working with latest quantifier added - 2.5 hours

**Comment by lndeaver** [comment]
11/10
uniqueness issue was fixed, but now quantifiers do not update with arrows when tiles are dragged.
(its a super back and forth thing right now where I can get one or the other but not both) - 1.5 hours

**Comment by lndeaver** [comment]
11/10
worked on trying to fix label updating with arrow - 1 hour

**Comment by lndeaver** [comment]
Reason for being unfinished:

The edit/display issue ended up taking more time than expected.
This issue was kind of dependent on the other issues with arrows was effecting how much this issue could be worked on in order to avoid having to rewrite/work a lot of code once arrows were fixed. Since those took longer to be fixed than expected, this issue wasn't able to be fully worked on/implemented to entirety due to not having arrows working mostly correct until late in the sprint.

What was able to get done with it was being able to add the quantifier and have it label the arrow, however updating the label with the line wasn't able to be finished due to not understanding/having a good way how, as well as knowing that the way arrows were going to work/be updated was being worked on and didn't want to dump hours of work into it and have it need redone/rewritten.

**Comment by ehinerdeer** [comment]
I worked on this for 1 hour

**Comment by lndeaver** [comment]
Logged time : 

11/22 
1 hour trying to fix the moving issue before working on a new issue

11/25
1 hour today with Eric pair programming to complete the issue
